from .BmpParser import BmpParser
from .CsvParser import CsvParser
from .ExcelParser import ExcelParser
from .FitsParser import FitsParser
from .GifParser import GifParser
from .JpgParser import JpgParser
from .HtmlTableParser import HtmlTableParser
from .JsonParser import JsonParser
from .NcParser import NcParser
from .PngParser import PngParser
from .StructuredParser import StructuredParser
from .TifParser import TifParser
